# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 175)
        MainWindow.setMinimumSize(QtCore.QSize(380, 175))
        MainWindow.setMaximumSize(QtCore.QSize(380, 175))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Users/vikto/.vscode/MyWork/Excange/money_icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(150, 70, 0);")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enter_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_currency.setGeometry(QtCore.QRect(20, 20, 140, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.enter_currency.setFont(font)
        self.enter_currency.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 240, 160);\n")
        self.enter_currency.setText("")
        self.enter_currency.setMaxLength(3)
        self.enter_currency.setCursorPosition(0)
        self.enter_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_currency.setObjectName("enter_currency")
        self.l_1 = QtWidgets.QLabel(self.centralwidget)
        self.l_1.setGeometry(QtCore.QRect(166, 20, 47, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.l_1.setFont(font)
        self.l_1.setAlignment(QtCore.Qt.AlignCenter)
        self.l_1.setObjectName("l_1")
        self.get_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.get_currency.setGeometry(QtCore.QRect(220, 20, 140, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.get_currency.setFont(font)
        self.get_currency.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 240, 160);")
        self.get_currency.setText("")
        self.get_currency.setMaxLength(3)
        self.get_currency.setCursorPosition(0)
        self.get_currency.setAlignment(QtCore.Qt.AlignCenter)
        self.get_currency.setObjectName("get_currency")
        self.enter_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_amount.setGeometry(QtCore.QRect(20, 70, 140, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.enter_amount.setFont(font)
        self.enter_amount.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 240, 160);")
        self.enter_amount.setText("")
        self.enter_amount.setMaxLength(14)
        self.enter_amount.setCursorPosition(0)
        self.enter_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_amount.setObjectName("enter_amount")
        self.l_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_2.setGeometry(QtCore.QRect(166, 70, 47, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.l_2.setFont(font)
        self.l_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_2.setObjectName("l_2")
        self.get_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.get_amount.setGeometry(QtCore.QRect(220, 70, 140, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.get_amount.setFont(font)
        self.get_amount.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 240, 160);")
        self.get_amount.setText("")
        self.get_amount.setMaxLength(14)
        self.get_amount.setCursorPosition(0)
        self.get_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.get_amount.setObjectName("get_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 340, 36))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(190, 90, 0);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exchange"))
        self.enter_currency.setPlaceholderText(_translate("MainWindow", "Enter currency"))
        self.l_1.setText(_translate("MainWindow", ">>"))
        self.get_currency.setPlaceholderText(_translate("MainWindow", "Get currency"))
        self.enter_amount.setPlaceholderText(_translate("MainWindow", "Enter amount"))
        self.l_2.setText(_translate("MainWindow", ">>"))
        self.get_amount.setPlaceholderText(_translate("MainWindow", "Get amount"))
        self.pushButton.setText(_translate("MainWindow", "   >>   &Excange   >>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
